repos:
  - repo: https://ghfast.top/github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.5
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  - repo: https://ghfast.top/github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        language_version: python3.10
        additional_dependencies:
          - pydantic
          - --index-url
          - https://pypi.tuna.tsinghua.edu.cn/simple/
  # No official ty hook for now, see https://github.com/astral-sh/ty/issues/269#issuecomment-3036849199
  - repo: local
    hooks:
      - id: ty-check
        name: ty-check
        language: python
        entry: ty check
        pass_filenames: false
        args: [--python=.venv/]
        additional_dependencies: [ty]
